/* =========================================================================
   SEED-77 PARITY — the engine must reproduce the APPROVED prototype's numbers
   EXACTLY. The expectations below were extracted by running the prototype's
   own pure functions (mulberry32 / seedFromString / genHistory /
   genSyntheticCloses, copied verbatim from prototypes/terminal-77/index.html)
   under node. toBe (===) on full-precision doubles: one bit of drift anywhere
   in the PRNG or GBM math fails the suite. Do NOT update these numbers to
   make a failing test pass — fix the engine; the user signed off on screens
   generated by exactly this sequence.
   ========================================================================= */
import { describe, it, expect, beforeAll } from "vitest";
import { mulberry32, seedFromString } from "./prng";
import { DataEngine, DEFAULT_SEED, HIST_POINTS } from "./dataEngine";
import { genSyntheticCloses } from "./ohlc";

beforeAll(() => { DataEngine.init(); });

describe("seed plumbing", () => {
  it("seedFromString is the prototype's FNV-1a (NVDA pins to 2591302102)", () => {
    expect(seedFromString("NVDA")).toBe(2591302102);
    expect(DEFAULT_SEED ^ seedFromString("NVDA")).toBe(-1703665253); // signed XOR is load-bearing
  });
  it("mulberry32(77) first draws match the prototype stream", () => {
    const rng = mulberry32(77);
    const a = rng(), b = rng();
    const rng2 = mulberry32(77);
    expect(rng2()).toBe(a); expect(rng2()).toBe(b); // deterministic restart
    expect(a).toBeGreaterThanOrEqual(0); expect(a).toBeLessThan(1);
  });
});

describe("DataEngine.init() — seed-77 world", () => {
  it("NVDA hist['1M'] first 5 closes are EXACT prototype values", () => {
    const m1 = DataEngine.get("NVDA").hist["1M"];
    expect(m1.length).toBe(HIST_POINTS["1M"]);
    expect(m1[0]).toBe(111.98244171522684);
    expect(m1[1]).toBe(112.8471952846768);
    expect(m1[2]).toBe(113.97374973285977);
    expect(m1[3]).toBe(112.84495137833359);
    expect(m1[4]).toBe(115.14405869280201);
    // tail normalises onto the personality base
    expect(m1[m1.length - 1]).toBe(126.39999999999999);
  });

  it("NVDA day series (hist['1D'] == day) first 5 + quote fields are EXACT", () => {
    const q = DataEngine.get("NVDA");
    expect(q.hist["1D"]).toBe(q.day); // 1D IS the live day series (same reference)
    expect(q.day[0]).toBe(124.80993827140543);
    expect(q.day[1]).toBe(124.53918796148422);
    expect(q.day[2]).toBe(125.02047322869521);
    expect(q.day[3]).toBe(125.02622039791613);
    expect(q.day[4]).toBe(125.74514612275225);
    expect(q.last).toBe(126.39999999999999);
    expect(q.prevClose).toBe(124.80993827140543);
    expect(q.dayPct).toBe(1.2739864714433891);
  });

  it("SPY hist['1M'] first 5 closes are EXACT prototype values", () => {
    const m1 = DataEngine.get("SPY").hist["1M"];
    expect(m1[0]).toBe(481.20561532023294);
    expect(m1[1]).toBe(481.8948048289028);
    expect(m1[2]).toBe(487.63205819407426);
    expect(m1[3]).toBe(490.0608110279444);
    expect(m1[4]).toBe(494.38943782892437);
  });

  it("genSyntheticCloses('NDX','1Y') — the alerts regime NDX proxy — is EXACT", () => {
    const ndx = genSyntheticCloses("NDX", HIST_POINTS["1Y"], "1Y");
    expect(ndx.length).toBe(240);
    expect(ndx[0]).toBe(270.09661149239042);
    expect(ndx[1]).toBe(272.306175361241);
    expect(ndx[2]).toBe(266.67628723288999);
    expect(ndx[239]).toBe(160.27675036197107);
  });

  it("re-init reproduces the identical world (screenshot-stable)", () => {
    const before = DataEngine.get("BTC-USD").hist["1Y"].slice(0, 10);
    DataEngine.init();
    expect(DataEngine.get("BTC-USD").hist["1Y"].slice(0, 10)).toEqual(before);
  });
});
